#ifndef header_h
#define header_h

String file1=
"<html>\r\n"
"<head>\r\n"
"<title>ESP8266 IP PDU</title>\r\n"
"<script type=\"text/javascript\">\r\n"
"window.onload=Pinstatus;\r\n"
"function Pinstatus(){\r\n"
"morestatus();\r\n"
"}\r\n"
"function morestatus(){\r\n"
"document.getElementById(\"description\").innerHTML = \"Processing Status\";\r\n"
"server = \"status/99\";\r\n"
"request = new XMLHttpRequest();\r\n"
"request.onreadystatechange = updateasyncstatus;\r\n"
"request.open(\"GET\", server, true);\r\n"
"request.send(null);\r\n"
"}\r\n"
"function updateasyncstatus(){\r\n"
"if ((request.readyState == 4) && (request.status == 200))\r\n"
"{\r\n"
"result = request.responseText;\r\n"
"document.getElementById(\"description\").innerHTML = result;\r\n"
"fullset = result.split(\"#\");\r\n"
"document.getElementById(\"description\").innerHTML = fullset;\r\n"
"for(i = 1; i < fullset.length; i++){\r\n"
"PinPair = fullset[i];\r\n"
"singleset = PinPair.split(\"=\");\r\n"
"PN = singleset[0];\r\n"
"Pinstatus = singleset[1];\r\n"
"if (PN = 12)\r\n"
"{\r\n"
"if (Pinstatus == 0)\r\n"
"{\r\n"
"text = \"Off\";\r\n"
"}\r\n"
"else\r\n"
"{\r\n"
"text = \"On\";\r\n"
"}\r\n"
"document.getElementById(\"texts\").innerHTML = text;\r\n"
"}\r\n"
"if (PN == 2 )\r\n"
"{\r\n"
"PinVal = parseInt(singleset[1]);\r\n"
"ValNum = \"valueDac\" + PN;\r\n"
"document.getElementById(\"time\").value = PinVal;\r\n"
"document.getElementById(\"valuetime\").innerHTML = PinVal;\r\n"
"}\r\n"
"}\r\n"
"}\r\n"
"}\r\n"
"function sendbutton(){\r\n"
"document.getElementById(\"description\").innerHTML = \"Processing Button Click\";\r\n"
"server = \"12/\";\r\n"
"request = new XMLHttpRequest();\r\n"
"request.onreadystatechange = updateasyncbutton;\r\n"
"request.open(\"GET\", server, true);\r\n"
"request.send(null);\r\n"
"}\r\n"
"function updateasyncbutton(){\r\n"
"if ((request.readyState == 4) && (request.status == 200))\r\n"
"{\r\n"
"result = request.responseText;\r\n"
"document.getElementById(\"description\").innerHTML = result;\r\n"
"singleset = result.split(\",\");\r\n"
"PinNum = singleset[0];\r\n"
"Pinstatus = singleset[1];\r\n"
"if (Pinstatus == 0)\r\n"
"{\r\n"
"text = \"Off\";\r\n"
"}\r\n"
"else\r\n"
"{\r\n"
"text = \"On\";\r\n"
"}\r\n"
"document.getElementById(\"texts\").innerHTML = text;\r\n"
"document.getElementById(\"description\").innerHTML = result;\r\n"
"}\r\n"
"}\r\n"
"function sendtime(value){\r\n"
"document.getElementById(\"time\").innerHTML=value;\r\n"
"document.getElementById(\"description\").innerHTML = \"Processing Slider\";\r\n"
"server = \"2/\" + value;\r\n"
"request = new XMLHttpRequest();\r\n"
"request.onreadystatechange = updateasynctime;\r\n"
"request.open(\"GET\", server, true);\r\n"
"request.send(null);\r\n"
"}\r\n"
"function updateasynctime(){\r\n"
"if ((request.readyState == 4) && (request.status == 200))\r\n"
"{\r\n"
"result = request.responseText;\r\n"
"single = result.split(\"#\");\r\n"
"first = single[0];\r\n"
"second = single[1];\r\n"
"singleset = first.split(\",\");\r\n"
"PinNum = singleset[0];\r\n"
"PinVal = parseInt(singleset[1]);\r\n"
"secondset = second.split(\",\");\r\n"
"text = \"On\";\r\n"
"document.getElementById(\"time\").value = PinVal;\r\n"
"document.getElementById(\"valuetime\").innerHTML = PinVal;\r\n"
"document.getElementById(\"description\").innerHTML = result;\r\n"
"document.getElementById(\"texts\").innerHTML = text;\r\n"
"}\r\n"
"}\r\n"
"</script>\r\n"
"</head>\r\n"
"<font face=\"Arial\">\r\n"
"<table name=\"Table\" border=\"1\" cellpadding=\"6\">\r\n"
"<tr> <th align=\"center\" colspan=\"6\" >Switch Button</th></tr>\r\n"
"<tr>\r\n"
"<td align=\"center\">\r\n"
"<button onclick=\"sendbutton();\"/>Power</button>\r\n"
"<p id=\"texts\">Off</p>"
"</td>\r\n"
"</tr>\r\n"
"<td align=\"center\">\r\n"
"Timer (in minutes)\r\n"
" <br>\r\n"
"<input type=\"range\" style=\"width: 240px; height: 30px;\" id=\"time\" min=\"0\" max=\"240\" value=\"0\" step=\"5\" onchange=\"sendtime(this.value);\"/>\r\n"
"<br>\r\n"
"<span id=\"valuetime\">0</span>\r\n"
"</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"<br><br>\r\n"
"<br><br>\r\n"
"<p id=\"description\"> - </p>\r\n"
"</font>\r\n"
"</html>\r\n";

#endif